import streamlit as st
import sys, os
import matplotlib.pyplot as plt
from wordcloud import WordCloud

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'src')))

from preprocessing import clean_text
from utils.model_loader import load_models

tfidf, logreg, xgb = load_models()

st.title("Advanced Analysis")

text_input = st.text_area("Enter Review")

model = st.selectbox("Select Model", ["Hybrid", "Logistic Regression", "XGBoost"])

if st.button("Analyze"):

    vec = tfidf.transform([clean_text(text_input)])

    prob_lr = logreg.predict_proba(vec)[0][1]
    prob_xgb = xgb.predict_proba(vec)[0][1]
    prob_hybrid = (prob_lr + prob_xgb) / 2

    def verdict_box(prob):
        if prob > 0.5:
            return "<div style='background:#fee2e2;padding:12px;border-radius:10px;color:#991b1b;font-size:18px'>Likely Fake Review</div>"
        else:
            return "<div style='background:#dcfce7;padding:12px;border-radius:10px;color:#166534;font-size:18px'>Likely Genuine Review</div>"

    # ---------------- HYBRID ----------------
    if model == "Hybrid":

        st.markdown("## Final Verdict")
        st.markdown(verdict_box(prob_hybrid), unsafe_allow_html=True)

        col1, col2 = st.columns(2)
        col1.markdown(f"<div style='background:#dbeafe;padding:10px;border-radius:8px'>Prediction<br>{prob_hybrid:.3f}</div>", unsafe_allow_html=True)
        col2.markdown(f"<div style='background:#ede9fe;padding:10px;border-radius:8px'>Confidence<br>{(1-abs(0.5-prob_hybrid)*2)*100:.2f}%</div>", unsafe_allow_html=True)

        st.markdown("### Model Comparison")
        st.caption("The comparison is based on probability scores generated by Logistic Regression and XGBoost for the same review input.")

        fig, ax = plt.subplots()
        ax.bar(["LogReg", "XGBoost"], [prob_lr, prob_xgb])
        st.pyplot(fig)

        # EXPLAINABILITY FIXED
        st.markdown("### Explainability")
        st.caption("Highlighted words indicate their contribution to the prediction. Red implies fake signals, green implies genuine patterns.")

        feature_names = tfidf.get_feature_names_out()
        coefs = logreg.coef_[0]
        vec_arr = vec.toarray()[0]

        weights = {feature_names[i]: coefs[i] for i in range(len(vec_arr)) if vec_arr[i] > 0}

        def highlight(w):
            key = w.lower()
            if key in weights:
                color = "rgba(255,0,0,0.25)" if weights[key] > 0 else "rgba(0,255,0,0.25)"
                return f"<span style='background:{color};padding:3px;border-radius:4px'>{w}</span>"
            return w

        highlighted = " ".join([highlight(w) for w in text_input.split()])
        st.markdown(f"<div style='background:#f8fafc;padding:10px;border-radius:10px'>{highlighted}</div>", unsafe_allow_html=True)

    # ---------------- LOG REG ----------------
    elif model == "Logistic Regression":

        st.markdown("## Final Verdict")
        st.markdown(verdict_box(prob_lr), unsafe_allow_html=True)

        col1, col2 = st.columns(2)
        col1.markdown(f"<div style='background:#dbeafe;padding:10px;border-radius:8px'>Prediction<br>{prob_lr:.3f}</div>", unsafe_allow_html=True)
        col2.markdown(f"<div style='background:#ede9fe;padding:10px;border-radius:8px'>Confidence<br>{(1-abs(0.5-prob_lr)*2)*100:.2f}%</div>", unsafe_allow_html=True)

        st.markdown("### About the Model")
        st.write("Logistic Regression is a linear model that assigns weights to words and predicts authenticity based on learned word patterns.")

        # EXPLAINABILITY
        st.markdown("### Explainability")
        st.caption("Highlighted words influence the prediction. Red indicates fake signals, green indicates genuine.")

        feature_names = tfidf.get_feature_names_out()
        coefs = logreg.coef_[0]
        vec_arr = vec.toarray()[0]

        weights = {feature_names[i]: coefs[i] for i in range(len(vec_arr)) if vec_arr[i] > 0}

        def highlight(w):
            key = w.lower()
            if key in weights:
                color = "rgba(255,0,0,0.25)" if weights[key] > 0 else "rgba(0,255,0,0.25)"
                return f"<span style='background:{color};padding:3px;border-radius:4px'>{w}</span>"
            return w

        highlighted = " ".join([highlight(w) for w in text_input.split()])
        st.markdown(f"<div style='background:#f8fafc;padding:10px;border-radius:10px'>{highlighted}</div>", unsafe_allow_html=True)

        # WORD CLOUD
        st.markdown("### Word Cloud")
        st.caption("Visual representation of important words influencing prediction.")

        wc = WordCloud(width=600, height=300).generate(text_input)
        st.image(wc.to_array())

    # ---------------- XGBOOST ----------------
    elif model == "XGBoost":

        st.markdown("## Final Verdict")
        st.markdown(verdict_box(prob_xgb), unsafe_allow_html=True)

        col1, col2 = st.columns(2)
        col1.markdown(f"<div style='background:#dbeafe;padding:10px;border-radius:8px'>Prediction<br>{prob_xgb:.3f}</div>", unsafe_allow_html=True)
        col2.markdown(f"<div style='background:#ede9fe;padding:10px;border-radius:8px'>Confidence<br>{(1-abs(0.5-prob_xgb)*2)*100:.2f}%</div>", unsafe_allow_html=True)

        st.markdown("### About the Model")
        st.write("XGBoost is an ensemble tree-based model that captures complex patterns in text using boosting techniques.")

        # EXPLAINABILITY
        st.markdown("### Explainability")
        st.caption("Highlighted words indicate influence on prediction.")

        feature_names = tfidf.get_feature_names_out()
        coefs = logreg.coef_[0]
        vec_arr = vec.toarray()[0]

        weights = {feature_names[i]: coefs[i] for i in range(len(vec_arr)) if vec_arr[i] > 0}

        def highlight(w):
            key = w.lower()
            if key in weights:
                color = "rgba(255,0,0,0.25)" if weights[key] > 0 else "rgba(0,255,0,0.25)"
                return f"<span style='background:{color};padding:3px;border-radius:4px'>{w}</span>"
            return w

        highlighted = " ".join([highlight(w) for w in text_input.split()])
        st.markdown(f"<div style='background:#f8fafc;padding:10px;border-radius:10px'>{highlighted}</div>", unsafe_allow_html=True)

        # WORD CLOUD
        st.markdown("### Word Cloud")
        st.caption("Key terms influencing prediction.")

        wc = WordCloud(width=600, height=300).generate(text_input)
        st.image(wc.to_array())
